version: "3"
services:

  vj-redis:
    image: redis:alpine
    container_name: vj-redis
    volumes:
      - ~/data/redis:/data

  vj-postgres:
    image: postgres:alpine
    container_name: vj-postgres
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password

  vj-backend:
    image:  registry.cn-hangzhou.aliyuncs.com/virtual-judge/virtual-judge:latest
    container_name: vj-backend
    depends_on:
      - vj-redis
      - vj-postgres
    environment:
      - REDIS_HOST=vj-redis
      - POSTGRES_HOST=vj-postgres
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password
    volumes:
      - ~/data/public:/public
      - ~/data/log:/data/log
      - ~/data/static:/data/static
    ports:
      - 0.0.0.0:8080:8080

