version: "3"
services:

  vj-redis:
    image: redis:4.0
    container_name: vj-redis
    volumes:
      - ~/data/redis:/data

  vj-postgres:
    image: postgres:10
    container_name: vj-postgres
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password

  vj-backend:
    image:  registry.cn-hangzhou.aliyuncs.com/virtual-judge/virtual-judge:latest
    container_name: vj-backend
    depends_on:
      - vj-redis
      - vj-postgres
    environment:
      - REDIS_HOST=vj-redis
      - POSTGRES_HOST=vj-postgres
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password
    volumes:
      - ~/data/public:/public:ro
      - ~/data/log:/data/log
      - ~/data/static:/data/static

  vj-nginx:
    image: nginx
    container_name: vj-nginx
    volumes:
      - ./nginx/nginx.conf:/nginx/nginx.conf
      - ~/data/public:/public:ro
      - ~/data/static:/static:ro
    depends_on:
      - vj-backend
    ports:
      - '0.0.0.0:80:80'
    command: /bin/bash -c "envsubst < /nginx/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

