version: "3"
services:

  vj-redis:
    image: redis:alpine
    container_name: vj-redis
    volumes:
      - ~/data/redis:/data

  vj-postgres:
    image: postgres:alpine
    container_name: vj-postgres
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password

  vj-backend:
    image:  registry.cn-hangzhou.aliyuncs.com/virtual-judge/virtual-judge:latest
    container_name: vj-backend
    depends_on:
      - vj-redis
      - vj-postgres
    environment:
      - REDIS_HOST=vj-redis
      - POSTGRES_HOST=vj-postgres
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password
    volumes:
      - ~/data/public:/public
      - ~/data/log:/data/log
      - ~/data/static:/data/static

  vj-frontend:
    image: registry.cn-hangzhou.aliyuncs.com/virtual-judge/virtual-judge-fe:latest
    container_name: vj-frontend

  vj-nginx:
    image: nginx
    container_name: vj-nginx
    volumes:
      - ./nginx:/nginx
      - ~/data/public:/public
      - ~/data/static:/static
    depends_on:
      - vj-backend
      - vj-frontend
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    command: /bin/bash -c "envsubst < /nginx/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

