version: "3"
services:

  vj-redis:
    image: redis:4.0
    container_name: vj-redis
    volumes:
      - ~/data/redis:/data

  vj-postgres:
    image: postgres:10
    container_name: vj-postgres
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password

  vj-phantomjs:
    image: wernight/phantomjs
    container_name: vj-phantomjs
    restart: always
    command: ['phantomjs', '--webdriver=8910']

  vj-backend:
    image:  registry.ap-northeast-1.aliyuncs.com/virtual-judge/virtual-judge:latest
    container_name: vj-backend
    depends_on:
      - vj-redis
      - vj-postgres
      - vj-phantomjs
    environment:
      - REDIS_HOST=vj-redis
      - POSTGRES_HOST=vj-postgres
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password
      - PHANTOMJS_HOST=vj-phantomjs
      - PHANTOMJS_PORT=8910
    volumes:
      - ~/data/public:/public
      - ~/data/log:/data/log
      - ~/data/static:/data/static

  vj-nginx:
    image: nginx
    container_name: vj-nginx
    volumes:
      - ./nginx:/nginx
      - ~/data/public:/public
      - ~/data/static:/static
    depends_on:
      - vj-backend
    ports:
      - '0.0.0.0:80:80'
    command: /bin/bash -c "envsubst < /nginx/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

