version: "3"
services:

  vj-redis:
    image: redis:4.0
    container_name: vj-redis
    restart: always
    volumes:
      - ~/data/redis:/data

  vj-postgres:
    image: postgres:10
    container_name: vj-postgres
    restart: always
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password

  vj-backend:
    image:  registry.ap-northeast-1.aliyuncs.com/virtual-judge/virtual-judge:latest
    container_name: vj-backend
    restart: always
    depends_on:
      - vj-redis
      - vj-postgres
    environment:
      - REDIS_HOST=vj-redis
      - POSTGRES_HOST=vj-postgres
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password
    volumes:
      - ~/data/public:/public
      - ~/data/log:/data/log
    ports:
      - "0.0.0.0:3000:80"
